-- ============================================================================
-- Rippling Employee ID backfill
-- ============================================================================
-- Source: Rippling pay-run templates downloaded 2026-06-03
--   - "template.csv"      (staff/W-2 entity, 7 rows)
--   - "template (1).csv"  (contractor/1099 entity, 270 rows)
--
-- Adds employees.rippling_employee_id, loads (emp_no, name) pairs from both
-- templates, auto-matches the unambiguous ones. Whatever doesn't match is
-- left blank — the payroll clerk fills in the few that actually show up on
-- payroll runs as she goes. Most of Amplified's ~2700 employee records will
-- never need a Rippling ID and stay null forever.
--
-- Run order (Supabase SQL editor runs each statement in a separate
-- connection, so we avoid temp tables — the roster lives inline in a CTE):
--   1. ALTER TABLE + CREATE INDEX (idempotent)
--   2. The big UPDATE with VALUES-based CTE
-- ============================================================================

-- ── Step 1. Schema (idempotent) ──────────────────────────────────────────
alter table employees
  add column if not exists rippling_employee_id integer;

create unique index if not exists employees_rippling_employee_id_uniq
  on employees (rippling_employee_id)
  where rippling_employee_id is not null;

-- ── Step 2. Auto-match — unambiguous full_name or payroll_name hits only ─
-- The roster is inlined as a VALUES list inside the CTE so the whole match
-- happens in one statement. Only unambiguous matches (exactly one Amplified
-- employee per Rippling name) are applied. Skips rows that already have a
-- value so re-runs and manual fixes are preserved.
with roster(rippling_emp_no, emp_name) as (
  values
    -- Staff template (template.csv) — 7 rows
    (2::integer,   'David Strang'::text),
    (13,  'Chris Travis'),
    (15,  'Devan Keska'),
    (21,  'Paulie Dunbar'),
    (109, 'Shelby/ Red Bowman'),
    (110, 'Cj Sparks'),
    (111, 'Brent Gonzalez'),
    -- Contractor template (template (1).csv) — 270 rows
    (1,   'Andie Topping'),
    (3,   'Ra Tigg'),
    (4,   'Xavier Wilson'),
    (5,   'Weston Leander'),
    (6,   'Demetrius Smith'),
    (7,   'Juanita Holt'),
    (9,   'Kurtay Witherspoon'),
    (11,  'Anthony Toohey'),
    (12,  'Cam Pasley'),
    (14,  'Krispy Culbertson'),
    (16,  'Hamadi Calhoun'),
    (17,  'Jack Stone'),
    (18,  'Jacob Jordan'),
    (19,  'Justin Nelson'),
    (20,  'Matthew Zender'),
    (22,  'Bobby Rackley'),
    (23,  'Bob Nugent'),
    (24,  'Ryan Lane'),
    (25,  'Samuel Shephard'),
    (26,  'Sah Nephew'),
    (27,  'Travis Moss'),
    (28,  'Twyla Brigham'),
    (29,  'Cameron Osborne'),
    (30,  'Kaleb Hency'),
    (32,  'Angel Harris'),
    (33,  'Josh Crenshaw'),
    (34,  'Moe McChesney'),
    (35,  'Dequan Jones'),
    (36,  'Ozzie Wiggins'),
    (37,  'Nolan Malloy'),
    (38,  'Dwayne Weaver'),
    (39,  'Christopher Van Benthuysen'),
    (40,  'Marley Creasy'),
    (41,  'Frank Moscarell'),
    (42,  'Marcus Riley'),
    (43,  'Christian Murray'),
    (44,  'Jacoby Hunter'),
    (45,  'Marina Myrmel-Smith'),
    (46,  'Kiara Whitset'),
    (47,  'Emily Layman'),
    (48,  'Jon Pheasant'),
    (49,  'Steven Ransom'),
    (50,  'Reginald Hooks'),
    (51,  'Unjron Harrington'),
    (52,  'Michael Collins'),
    (53,  'Joey Scorza'),
    (54,  'Lindsay Devilbliss'),
    (55,  'Peyton Degrange'),
    (56,  'Taylor Harris'),
    (57,  'Tyree Greene'),
    (58,  'Jerome Lancaster'),
    (59,  'Matthew McCullough'),
    (60,  'Melly Burwell'),
    (61,  'Shane Coultas'),
    (62,  'Michael Ogu'),
    (63,  'Ricardo Obregon'),
    (64,  'Matt Harris'),
    (65,  'Reginald Jackson'),
    (66,  'Nicolas Baradawill'),
    (67,  'April Dowdy'),
    (68,  'Georgia Agius'),
    (69,  'Jesse Barker'),
    (70,  'Lorena Bermudez'),
    (71,  'Michael Cupit'),
    (72,  'Johnathan Bruno'),
    (73,  'Cortez Davis'),
    (74,  'Alan Gordon'),
    (75,  'Sam Edwards'),
    (76,  'Chris Grabau'),
    (77,  'Kelly Lewis'),
    (78,  'Cody Sweatt LLC'),
    (79,  'Sean Brown'),
    (80,  'Drew Francis'),
    (81,  'Brian Cooper'),
    (82,  'Josh Younger'),
    (83,  'Caleb Haney'),
    (84,  'Jeremiah Frye'),
    (85,  'Sean Hall'),
    (86,  'Kyle Griffin'),
    (87,  'Anthony Mosquera'),
    (88,  'Terry Lakimayion'),
    (89,  'Keith Hayes'),
    (90,  'Mark Vergara'),
    (91,  'Thomas McKinney'),
    (92,  'Chris Pitman'),
    (93,  'Evan Morton'),
    (94,  'Michael Johnson'),
    (95,  'Dom Manno'),
    (96,  'Mia Simpson'),
    (97,  'Steven Olmedo'),
    (98,  'Tim Tanner'),
    (99,  'Brandon Rorick'),
    (100, 'Dakota Prasatek'),
    (101, 'Jordan Preciado'),
    (102, 'Markese Reaves'),
    (103, 'BEANZ Surles'),
    (104, 'Maggie Mamani Vargas'),
    (105, 'David Vergara'),
    (106, 'Savanna Waltermier'),
    (107, 'Steven Vergara'),
    (108, 'Steve Vergara'),
    (112, 'Justin Pruiett'),
    (113, 'Devaughn Jones'),
    (114, 'Robin Forse-Wilcox'),
    (115, 'Nick Bufka'),
    (116, 'Christopher Adams'),
    (117, 'Marvin Hernandez'),
    (118, 'Ashton Hatfield'),
    (119, 'Anthony Higginbotham'),
    (120, 'Preston Harmon'),
    (121, 'Penelope Stitzel'),
    (122, 'Monte Moore'),
    (123, 'Shay Poling'),
    (124, 'Julian Cole'),
    (125, 'David Leichliter'),
    (126, 'Orlando Collins'),
    (127, 'Timothy Yeager'),
    (128, 'Tiffany Cooksey'),
    (129, 'Ray Andrews'),
    (130, 'Sam Zmuda'),
    (131, 'Devon Stroman'),
    (132, 'Ravin Booher'),
    (133, 'Ray Davis'),
    (134, 'Brian Tapia'),
    (135, 'Fisher Gotcher'),
    (136, 'Brent Babin'),
    (137, 'Blaine Holliday'),
    (138, 'Elizabeth Stutes'),
    (139, 'Heavy Galore'),
    (140, 'Jayden Olds'),
    (141, 'Braylin Stewart'),
    (142, 'Eli Falcone'),
    (143, 'Lacey Dubuisson'),
    (144, 'Jonas Mendez'),
    (145, 'Isaiah Holiday'),
    (146, 'Jeffrey Eckel'),
    (147, 'Vegas Hutchinson'),
    (148, 'Davon Stroman'),
    (149, 'Mika Arter'),
    (150, 'Jamal Copeland-Harris'),
    (151, 'E Rudolph'),
    (153, 'Peter Vaughan'),
    (154, 'Jasmyn Bland'),
    (155, 'Jessica Harris'),
    (156, 'Sarah Ruehl'),
    (157, 'Eilezbeth Hubbard'),
    (158, 'Vanessa Benavides'),
    (159, 'Kenith Mitchell'),
    (160, 'Arias Smith'),
    (161, 'Jake Utley'),
    (162, 'Tiffanie Boyd'),
    (163, 'Nick Stacy'),
    (164, 'Amanda Dehaan'),
    (165, 'Alf Norris'),
    (166, 'Will Pfrang'),
    (167, 'Tink Champ'),
    (168, 'Alex Zablah'),
    (169, 'Maurice Wright'),
    (170, 'Lamonica Lee'),
    -- Anthony Thigpen appears twice in Rippling (171, 174). We keep 171 with
    -- the real name; 174 gets a unique label so it won't auto-match anyone.
    -- Connor reconciles manually — see project_employee_dedup.md.
    (171, 'Anthony Thigpen'),
    (174, 'Anthony Thigpen (Rippling dupe #174)'),
    (172, 'Levi Malech'),
    (173, 'Hannah Couch'),
    (175, 'Markell Reed'),
    (176, 'T Berry'),
    (177, 'Duct Tape Pendergast'),
    (178, 'Bobby Beck'),
    (179, 'Spicely Bland'),
    (180, 'Mario Mosqueda'),
    (181, 'Anthony Screnci'),
    (182, 'Amber Wheeler'),
    (183, 'Bianca Hernandez'),
    (184, 'Jakob Starzyk'),
    (185, 'Brandon Petiti'),
    (186, 'Andy Head'),
    (187, 'Chloe Moore'),
    (188, 'Brian Slingerland'),
    (189, 'Sean Graham'),
    (190, 'James Yost'),
    (191, 'Jason Benitez'),
    (192, 'Kerri Kramer'),
    (193, 'Peter Saldana'),
    (194, 'Sean Mayes'),
    (195, 'Justin Malave'),
    (196, 'Lupe Rodriguez'),
    (197, 'Michael Vaccarino'),
    (198, 'Jacob Shapiro'),
    (199, 'Devon Taylor'),
    (200, 'Michael Gawlik'),
    (201, 'Dylon Garvin'),
    (202, 'Vincent Banks'),
    (203, 'Tim Poole'),
    (204, 'Stephen Sadlowski'),
    (205, 'Gerald Crumblin'),
    (206, 'Evie Adams'),
    (207, 'Jean Seal'),
    (208, 'Nate Johnson'),
    (209, 'Mohamed Ba'),
    (210, 'Jamall Walker'),
    (211, 'Kiki Martijn'),
    (212, 'Kevin McCoy'),
    (213, 'John Miller'),
    (214, 'Travis Obermeyer'),
    (215, 'Nick Huth'),
    (216, 'Will Beller'),
    (217, 'Evan Babin'),
    (218, 'Madison Warren'),
    (219, 'Mason dalkiewicz'),
    (220, 'Christopher Elliott'),
    (221, 'C.K. Milam'),
    (222, 'Eddie Alspaugh'),
    (223, 'Doug Kelly'),
    (224, 'Wesley Belaire'),
    (225, 'Ninja Bermudez'),
    (226, 'Paul Brennan'),
    (227, 'Odell Burns'),
    (228, 'Justin Burress'),
    (230, 'Pyro Burns'),
    (231, 'Kevin Davis'),
    (232, 'Christopher Cook'),
    (233, 'Nicole Cox'),
    (234, 'Nina Duty'),
    (235, 'Hunter Fowler'),
    (236, 'David Finney'),
    (237, 'Rey Ferguson'),
    (238, 'Elissa Gaus'),
    (239, 'Stephen Fox'),
    (240, 'Jamal Garel'),
    (241, 'James Grabill'),
    (242, 'Khayle Howard'),
    (243, 'Dakota Hulsey'),
    (244, 'Jacob Hamilton'),
    (245, 'Richard Hufflin'),
    (246, 'Artise James'),
    (247, 'Conor Gibney'),
    (248, 'Brett Johnson'),
    (249, 'Donte Johnson'),
    (250, 'James Martin'),
    (251, 'Michelle Mack'),
    (252, 'Soni Haze'),
    (253, 'Tristan Meier'),
    (254, 'Mantis McGowan'),
    (255, 'Narazjia Hall'),
    (256, 'Ray Neal'),
    (257, 'Calvin Parker'),
    (258, 'Camden Gunther'),
    (259, 'Brandon Patterson'),
    (260, 'Terence Peay'),
    (261, 'Falon Smith'),
    (262, 'Mark Hanna'),
    (263, 'HENRY Hawkins'),
    (264, 'Joseph Spaziani'),
    (265, 'Desiree Smoot'),
    (266, 'Delonte Scott'),
    (267, 'Griselda Sandoval'),
    (268, 'Dominick Williams'),
    (269, 'Megan Mastromonaco'),
    (270, 'Matthew Spivey'),
    (271, 'Colton Kivimaki'),
    (272, 'Cameron Springer'),
    (273, 'Cory Treadway'),
    (274, 'Robert Westfall'),
    (275, 'Meah Reid'),
    (276, 'Danielle White'),
    (277, 'Dillon Schumacher'),
    (278, 'Scoobi Gilbert'),
    (279, 'Dustin Tanner'),
    (280, 'Kyle Kaufman'),
    (281, 'Chris Stewart')
),
matches as (
  select r.rippling_emp_no, e.employee_key
  from roster r
  join employees e
    on lower(trim(e.full_name))    = lower(trim(r.emp_name))
    or lower(trim(e.payroll_name)) = lower(trim(r.emp_name))
),
unique_matches as (
  select rippling_emp_no, min(employee_key) as employee_key
  from matches
  group by rippling_emp_no
  having count(*) = 1
)
update employees e
set rippling_employee_id = um.rippling_emp_no
from unique_matches um
where um.employee_key = e.employee_key
  and e.rippling_employee_id is null;
