// Canonical Rippling import header order — from template (1)-1.csv (2026-07-10).
// DO NOT reorder: Rippling matches columns by exact header text, and the
// contractor import expects this column order. Regenerate if Connor changes
// Rippling earning types.
export const RIPPLING_HEADERS = [
  "Rippling Emp No",
  "Employee Name",
  "Workweek",
  "Rigger",
  "Shift ID",
  "Contractor Hourly Hours",
  "Contractor Hourly Rate",
  "Contractor Hourly Amount",
  "Payable Cash Tips",
  "Regular Rate of Pay (Premium) Hours",
  "Regular Rate of Pay (Premium) Rate",
  "Regular Rate of Pay (Premium) Amount",
  "Rigger Hours",
  "Rigger Rate",
  "Rigger Amount",
  "Rigger Earning Period",
  "Rigger overtime (1.5x base) Hours",
  "Rigger overtime (1.5x base) Rate",
  "Rigger overtime (1.5x base) Amount",
  "Rigger overtime (1.5x base) Earning Period",
  "Rigger double overtime (2.0x base) Hours",
  "Rigger double overtime (2.0x base) Rate",
  "Rigger double overtime (2.0x base) Amount",
  "Rigger double overtime (2.0x base) Earning Period",
  "Fork Hours",
  "Fork Rate",
  "Fork Amount",
  "Fork Earning Period",
  "Fork overtime (1.5x base) Hours",
  "Fork overtime (1.5x base) Rate",
  "Fork overtime (1.5x base) Amount",
  "Fork overtime (1.5x base) Earning Period",
  "Fork double overtime (2.0x base) Hours",
  "Fork double overtime (2.0x base) Rate",
  "Fork double overtime (2.0x base) Amount",
  "Fork double overtime (2.0x base) Earning Period",
  "Lead Hours",
  "Lead Rate",
  "Lead Amount",
  "Lead Earning Period",
  "Lead overtime (1.5x base) Hours",
  "Lead overtime (1.5x base) Rate",
  "Lead overtime (1.5x base) Amount",
  "Lead overtime (1.5x base) Earning Period",
  "Lead double overtime (2.0x base) Hours",
  "Lead double overtime (2.0x base) Rate",
  "Lead double overtime (2.0x base) Amount",
  "Lead double overtime (2.0x base) Earning Period",
  "Day Rate 1 Hours",
  "Day Rate 1 Rate",
  "Day Rate 1 Amount",
  "Day Rate 1 Earning Period",
  "Day Rate 1 overtime (1.5x base) Hours",
  "Day Rate 1 overtime (1.5x base) Rate",
  "Day Rate 1 overtime (1.5x base) Amount",
  "Day Rate 1 overtime (1.5x base) Earning Period",
  "Day Rate 1 double overtime (2.0x base) Hours",
  "Day Rate 1 double overtime (2.0x base) Rate",
  "Day Rate 1 double overtime (2.0x base) Amount",
  "Day Rate 1 double overtime (2.0x base) Earning Period",
  "Climber Hours",
  "Climber Rate",
  "Climber Amount",
  "Climber Earning Period",
  "Climber overtime (1.5x base) Hours",
  "Climber overtime (1.5x base) Rate",
  "Climber overtime (1.5x base) Amount",
  "Climber overtime (1.5x base) Earning Period",
  "Climber double overtime (2.0x base) Hours",
  "Climber double overtime (2.0x base) Rate",
  "Climber double overtime (2.0x base) Amount",
  "Climber double overtime (2.0x base) Earning Period",
  "Coordinator Hours",
  "Coordinator Rate",
  "Coordinator Amount",
  "Coordinator Earning Period",
  "Coordinator overtime (1.5x base) Hours",
  "Coordinator overtime (1.5x base) Rate",
  "Coordinator overtime (1.5x base) Amount",
  "Coordinator overtime (1.5x base) Earning Period",
  "Coordinator double overtime (2.0x base) Hours",
  "Coordinator double overtime (2.0x base) Rate",
  "Coordinator double overtime (2.0x base) Amount",
  "Coordinator double overtime (2.0x base) Earning Period",
  "Missed Pay Hours",
  "Missed Pay Rate",
  "Missed Pay Amount",
  "Missed Pay overtime (1.5x base) Hours",
  "Missed Pay overtime (1.5x base) Rate",
  "Missed Pay overtime (1.5x base) Amount",
  "Missed Pay double overtime (2.0x base) Hours",
  "Missed Pay double overtime (2.0x base) Rate",
  "Missed Pay double overtime (2.0x base) Amount",
  "Paystub Note",
] as const;
